CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64) NOT NULL,
    name VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS "user_email_uniq_index"
    ON "user" (email);

CREATE INDEX IF NOT EXISTS "user_name_index"
    ON "user" (name);

CREATE TABLE IF NOT EXISTS "item" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
    name VARCHAR(64),
    description VARCHAR(1024),
    is_available BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS "item_owner_index"
    ON "item" (owner_id, is_available);

CREATE INDEX IF NOT EXISTS "item_name_index"
    ON "item" (name, is_available);

CREATE INDEX IF NOT EXISTS "item_desc_index"
    ON "item" (description, is_available);

CREATE TYPE booking_status AS ENUM ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');

CREATE TABLE IF NOT EXISTS "booking" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER REFERENCES "item" (id) ON DELETE CASCADE,
    booker_id INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
    begin_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status booking_status NOT NULL DEFAULT 'WAITING'
);
